AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  meetzee_lambda
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Resources:
  firestoreConnectionTestFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: firestoreConnectionTest
      CodeUri: firestoreConnectionTest/
      Handler: firestoreConnectionTest.lambdaHandler
      Runtime: nodejs10.x
      Policies:
        - AWSLambdaVPCAccessExecutionRole
      MemorySize: 256
      Events:
        documentdbConnectionTest:
          Type: Api
          Properties:
            Path: /firestoreConnectionTest
            Method: get
  
  createUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: createUserFunction
      CodeUri: createUser/
      Handler: createUser.lambdaHandler
      Runtime: nodejs10.x
      Policies:
        - AWSLambdaVPCAccessExecutionRole
      MemorySize: 256
      Events:
        documentdbConnectionTest:
          Type: Api
          Properties:
            Path: /createUser
            Method: get

  loginUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: loginUserFunction
      CodeUri: loginUser/
      Handler: loginUser.lambdaHandler
      Runtime: nodejs10.x
      Policies:
        - AWSLambdaVPCAccessExecutionRole
      MemorySize: 256
      Events:
        documentdbConnectionTest:
          Type: Api
          Properties:
            Path: /loginUser
            Method: get

Outputs:
  firestoreConnectionTestApi:
    Description: "API Gateway endpoint URL for Prod stage for documentdbConnectionTest function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/firestoreConnectionTest/"
  firestoreConnectionTestFunction:
    Description: "firestoreConnectionTest Lambda Function ARN"
    Value: !GetAtt firestoreConnectionTestFunction.Arn

  createUserApi:
    Description: "API Gateway endpoint URL for Prod stage for Create User function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/createUser/"
  createUserFunction:
    Description: "Create User Lambda Function ARN"
    Value: !GetAtt createUserFunction.Arn
  
  loginUserApi:
    Description: "API Gateway endpoint URL for Prod stage for login User function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/loginUser/"
  createUserFunction:
    Description: "Create User Lambda Function ARN"
    Value: !GetAtt loginUserFunction.Arn

