AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  meetzee_lambda
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Resources:
  firestoreConnectionTestFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: firestoreConnectionTest
      CodeUri: firestoreConnectionTest/
      Handler: firestoreConnectionTest.lambdaHandler
      Runtime: nodejs8.10
      Policies:
        - AWSLambdaVPCAccessExecutionRole
      MemorySize: 256
      Events:
        firestoreConnectionTest:
          Type: Api
          Properties:
            Path: /firestoreConnectionTest
            Method: get
  
  createUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: createUserFunction
      CodeUri: createUser/
      Handler: createUser.lambdaHandler
      Runtime: nodejs8.10
      Policies:
        - AWSLambdaVPCAccessExecutionRole
      MemorySize: 256
      Events:
        createUserFunction:
          Type: Api
          Properties:
            Path: /createUser
            Method: get

  loginUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: loginUserFunction
      CodeUri: loginUser/
      Handler: loginUser.lambdaHandler
      Runtime: nodejs8.10
      Policies:
        - AWSLambdaVPCAccessExecutionRole
      MemorySize: 256
      Events:
        loginUserFunction:
          Type: Api
          Properties:
            Path: /loginUser
            Method: get
  
  updateFriendsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: updateFriendsFunction
      CodeUri: updateFriends/
      Handler: updateFriends.lambdaHandler
      Runtime: nodejs8.10
      Policies:
        - AWSLambdaVPCAccessExecutionRole
      MemorySize: 256
      Events:
        updateFriendsFunction:
          Type: Api
          Properties:
            Path: /updateFriends
            Method: get

  updateScheduleFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: updateScheduleFunction
      CodeUri: updateSchedule/
      Handler: updateSchedule.lambdaHandler
      Runtime: nodejs8.10
      Policies:
        - AWSLambdaVPCAccessExecutionRole
      MemorySize: 256
      Events:
        updateScheduleFunction:
          Type: Api
          Properties:
            Path: /updateSchedule
            Method: get

  findSlotFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: findSlotFunction
      CodeUri: findSlot/
      Handler: findSlot.lambdaHandler
      Runtime: nodejs8.10
      Policies:
        - AWSLambdaVPCAccessExecutionRole
      MemorySize: 384
      Events:
        findSlotFunction:
          Type: Api
          Properties:
            Path: /findSlot
            Method: get
  
  setEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: setEventFunction
      CodeUri: setEvent/
      Handler: setEvent.lambdaHandler
      Runtime: nodejs8.10
      Policies:
        - AWSLambdaVPCAccessExecutionRole
      MemorySize: 256
      Events:
        setEventFunction:
          Type: Api
          Properties:
            Path: /setEvent
            Method: get
  
  deleteEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: deleteEventFunction
      CodeUri: deleteEvent/
      Handler: deleteEvent.lambdaHandler
      Runtime: nodejs8.10
      Policies:
        - AWSLambdaVPCAccessExecutionRole
      MemorySize: 256
      Events:
        deleteEventFunction:
          Type: Api
          Properties:
            Path: /deleteEvent
            Method: get

  getUserDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getUserDataFunction
      CodeUri: getUserData/
      Handler: getUserData.lambdaHandler
      Runtime: nodejs8.10
      Policies:
        - AWSLambdaVPCAccessExecutionRole
      MemorySize: 256
      Events:
        getUserDataFunction:
          Type: Api
          Properties:
            Path: /getUserData
            Method: get

  modifyEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: modifyEventFunction
      CodeUri: modifyEvent/
      Handler: modifyEvent.lambdaHandler
      Runtime: nodejs8.10
      Policies:
        - AWSLambdaVPCAccessExecutionRole
      MemorySize: 256
      Events:
        modifyEventFunction:
          Type: Api
          Properties:
            Path: /modifyEvent
            Method: get

  approveRescheduleFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: approveRescheduleFunction
      CodeUri: approveReschedule/
      Handler: approveReschedule.lambdaHandler
      Runtime: nodejs8.10
      Policies:
        - AWSLambdaVPCAccessExecutionRole
      MemorySize: 256
      Events:
        approveRescheduleFunction:
          Type: Api
          Properties:
            Path: /approveReschedule
            Method: get
  
  acceptRescheduleSolutionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: acceptRescheduleSolutionFunction
      CodeUri: acceptRescheduleSolution/
      Handler: acceptRescheduleSolution.lambdaHandler
      Runtime: nodejs8.10
      Policies:
        - AWSLambdaVPCAccessExecutionRole
      MemorySize: 256
      Events:
        acceptRescheduleSolutionFunction:
          Type: Api
          Properties:
            Path: /acceptRescheduleSolution
            Method: get
  
  resetLockFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: resetLockFunction
      CodeUri: resetLock/
      Handler: resetLock.lambdaHandler
      Runtime: nodejs8.10
      Policies:
        - AWSLambdaVPCAccessExecutionRole
      MemorySize: 256
      Events:
        resetLockFunction:
          Type: Api
          Properties:
            Path: /resetLock
            Method: get

  clearNotificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: clearNotificationFunction
      CodeUri: clearNotification/
      Handler: clearNotification.lambdaHandler
      Runtime: nodejs8.10
      Policies:
        - AWSLambdaVPCAccessExecutionRole
      MemorySize: 256
      Events:
        clearNotificationFunction:
          Type: Api
          Properties:
            Path: /clearNotification
            Method: get

Outputs:
  firestoreConnectionTestApi:
    Description: "API Gateway endpoint URL for Prod stage for documentdbConnectionTest function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/firestoreConnectionTest/"
  firestoreConnectionTestFunction:
    Description: "firestoreConnectionTest Lambda Function ARN"
    Value: !GetAtt firestoreConnectionTestFunction.Arn

  createUserApi:
    Description: "API Gateway endpoint URL for Prod stage for Create User function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/createUser/"
  createUserFunction:
    Description: "Create User Lambda Function ARN"
    Value: !GetAtt createUserFunction.Arn
  
  loginUserApi:
    Description: "API Gateway endpoint URL for Prod stage for login user function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/loginUser/"
  loginUserFunction:
    Description: "Login User Lambda Function ARN"
    Value: !GetAtt loginUserFunction.Arn

  updateFriendsApi:
    Description: "API Gateway endpoint URL for Prod stage for update friends function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/updateFriends/"
  updateFriendsFunction:
    Description: "Update friends Lambda Function ARN"
    Value: !GetAtt updateFriendsFunction.Arn

  updateScheduleApi:
    Description: "API Gateway endpoint URL for Prod stage for update schedule function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/updateSchedule/"
  updateScheduleFunction:
    Description: "Update schedule Lambda Function ARN"
    Value: !GetAtt updateScheduleFunction.Arn

  findSlotApi:
    Description: "API Gateway endpoint URL for Prod stage for find slot function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/findSlot/"
  findSlotFunction:
    Description: "find slot Lambda Function ARN"
    Value: !GetAtt findSlotFunction.Arn

  setEventApi:
    Description: "API Gateway endpoint URL for Prod stage for set event function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/setEvent/"
  findSlotFunction:
    Description: "set event Lambda Function ARN"
    Value: !GetAtt setEventFunction.Arn

  deleteEventApi:
    Description: "API Gateway endpoint URL for Prod stage for delete event function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/deleteEvent/"
  findSlotFunction:
    Description: "delete event Lambda Function ARN"
    Value: !GetAtt deleteEventFunction.Arn

  getUserDataApi:
    Description: "API Gateway endpoint URL for Prod stage for get user data function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/getUserData/"
  getUserDataFunction:
    Description: "get user data Lambda Function ARN"
    Value: !GetAtt getUserDataFunction.Arn

  modifyEventApi:
    Description: "API Gateway endpoint URL for Prod stage for modify event function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/modifyEvent/"
  modifyEventFunction:
    Description: "modify event Lambda Function ARN"
    Value: !GetAtt modifyEventFunction.Arn

  approveRescheduleApi:
    Description: "API Gateway endpoint URL for Prod stage for approve reschedule function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/approveReschedule/"
  approveRescheduleFunction:
    Description: "approve reschedule Lambda Function ARN"
    Value: !GetAtt approveRescheduleFunction.Arn

  acceptRescheduleSolutionApi:
    Description: "API Gateway endpoint URL for Prod stage for accept reschedule solution function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/approveReschedule/"
  acceptRescheduleSolutionFunction:
    Description: "accept reschedule solution Lambda Function ARN"
    Value: !GetAtt acceptRescheduleSolutionFunction.Arn

  resetLockApi:
    Description: "API Gateway endpoint URL for Prod stage for reset lock function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/approveReschedule/"
  resetLockFunction:
    Description: "reset lock Lambda Function ARN"
    Value: !GetAtt resetLockFunction.Arn

  clearNotificationApi:
    Description: "API Gateway endpoint URL for Prod stage for clear notification function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/clearNotification/"
  clearNotificationFunction:
    Description: "clear notification Lambda Function ARN"
    Value: !GetAtt clearNotificationFunction.Arn