AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  meetzee_lambda
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Resources:
  firestoreConnectionTestFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: firestoreConnectionTest
      CodeUri: firestoreConnectionTest/
      Handler: firestoreConnectionTest.lambdaHandler
      Runtime: nodejs8.10
      Policies:
        - AWSLambdaVPCAccessExecutionRole
      MemorySize: 256
      Events:
        firestoreConnectionTest:
          Type: Api
          Properties:
            Path: /firestoreConnectionTest
            Method: get
  
  createUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: createUserFunction
      CodeUri: createUser/
      Handler: createUser.lambdaHandler
      Runtime: nodejs8.10
      Policies:
        - AWSLambdaVPCAccessExecutionRole
      MemorySize: 256
      Events:
        createUserFunction:
          Type: Api
          Properties:
            Path: /createUser
            Method: get

  loginUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: loginUserFunction
      CodeUri: loginUser/
      Handler: loginUser.lambdaHandler
      Runtime: nodejs8.10
      Policies:
        - AWSLambdaVPCAccessExecutionRole
      MemorySize: 256
      Events:
        loginUserFunction:
          Type: Api
          Properties:
            Path: /loginUser
            Method: get
  
  updateFriendsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: updateFriendsFunction
      CodeUri: updateFriends/
      Handler: updateFriends.lambdaHandler
      Runtime: nodejs8.10
      Policies:
        - AWSLambdaVPCAccessExecutionRole
      MemorySize: 256
      Events:
        updateFriendsFunction:
          Type: Api
          Properties:
            Path: /updateFriends
            Method: get

  updateScheduleFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: updateScheduleFunction
      CodeUri: updateSchedule/
      Handler: updateSchedule.lambdaHandler
      Runtime: nodejs8.10
      Policies:
        - AWSLambdaVPCAccessExecutionRole
      MemorySize: 256
      Events:
        updateScheduleFunction:
          Type: Api
          Properties:
            Path: /updateSchedule
            Method: get

  findSlotFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: findSlotFunction
      CodeUri: findSlot/
      Handler: findSlot.lambdaHandler
      Runtime: nodejs8.10
      Policies:
        - AWSLambdaVPCAccessExecutionRole
      MemorySize: 256
      Events:
        findSlotFunction:
          Type: Api
          Properties:
            Path: /findSlot
            Method: get
  
  setEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: setEventFunction
      CodeUri: setEvent/
      Handler: setEvent.lambdaHandler
      Runtime: nodejs8.10
      Policies:
        - AWSLambdaVPCAccessExecutionRole
      MemorySize: 256
      Events:
        setEventFunction:
          Type: Api
          Properties:
            Path: /setEvent
            Method: get
  
  deleteEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: deleteEventFunction
      CodeUri: deleteEvent/
      Handler: deleteEvent.lambdaHandler
      Runtime: nodejs8.10
      Policies:
        - AWSLambdaVPCAccessExecutionRole
      MemorySize: 256
      Events:
        deleteEventFunction:
          Type: Api
          Properties:
            Path: /deleteEvent
            Method: get

  getUserDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getUserDataFunction
      CodeUri: getUserData/
      Handler: getUserData.lambdaHandler
      Runtime: nodejs8.10
      Policies:
        - AWSLambdaVPCAccessExecutionRole
      MemorySize: 256
      Events:
        getUserDataFunction:
          Type: Api
          Properties:
            Path: /getUserData
            Method: get

Outputs:
  firestoreConnectionTestApi:
    Description: "API Gateway endpoint URL for Prod stage for documentdbConnectionTest function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/firestoreConnectionTest/"
  firestoreConnectionTestFunction:
    Description: "firestoreConnectionTest Lambda Function ARN"
    Value: !GetAtt firestoreConnectionTestFunction.Arn

  createUserApi:
    Description: "API Gateway endpoint URL for Prod stage for Create User function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/createUser/"
  createUserFunction:
    Description: "Create User Lambda Function ARN"
    Value: !GetAtt createUserFunction.Arn
  
  loginUserApi:
    Description: "API Gateway endpoint URL for Prod stage for login user function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/loginUser/"
  loginUserFunction:
    Description: "Login User Lambda Function ARN"
    Value: !GetAtt loginUserFunction.Arn

  updateFriendsApi:
    Description: "API Gateway endpoint URL for Prod stage for update friends function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/updateFriends/"
  updateFriendsFunction:
    Description: "Update friends Lambda Function ARN"
    Value: !GetAtt updateFriendsFunction.Arn

  updateScheduleApi:
    Description: "API Gateway endpoint URL for Prod stage for update schedule function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/updateSchedule/"
  updateScheduleFunction:
    Description: "Update schedule Lambda Function ARN"
    Value: !GetAtt updateScheduleFunction.Arn

  findSlotApi:
    Description: "API Gateway endpoint URL for Prod stage for find slot function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/findSlot/"
  findSlotFunction:
    Description: "find slot Lambda Function ARN"
    Value: !GetAtt findSlotFunction.Arn

  setEventApi:
    Description: "API Gateway endpoint URL for Prod stage for set event function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/setEvent/"
  findSlotFunction:
    Description: "set event Lambda Function ARN"
    Value: !GetAtt setEventFunction.Arn

  deleteEventApi:
    Description: "API Gateway endpoint URL for Prod stage for delete event function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/deleteEvent/"
  findSlotFunction:
    Description: "delete event Lambda Function ARN"
    Value: !GetAtt deleteEventFunction.Arn

  getUserDataApi:
    Description: "API Gateway endpoint URL for Prod stage for get user data function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/getUserData/"
  getUserDataFunction:
    Description: "get user data Lambda Function ARN"
    Value: !GetAtt getUserDataFunction.Arn